Cleaning up setup and more helpful tip

diff --git a/gitlab-ci-extend b/gitlab-ci-extend
--- a/gitlab-ci-extend
+++ b/gitlab-ci-extend
@@ -1,5 +1,63 @@
 #!/bin/bash -i
 
+vars_parse--setup() {
+  CURDIR=$1
+  shift
+  DEPLOYDIR=$1
+  cd $CURDIR
+  instance=$(basename `pwd`)
+  INSTANCE=${2:-$instance}
+  RELOADCOMMAND=${3:-'pm2 delete \\"'$INSTANCE'\\" || pm2 list; cd '$DEPLOYDIR' && pm2 start npm --name \\"'$INSTANCE'\\" -- start || pm2 list'}
+  BUILDSCRIPT=${4:-'npm install;'}
+  NODEVERSION=${5:-'10.17.0'}
+  DOCKERNODE=${6:-'node:10.17.0-jessie'}
+  DIR=$(dirname $0)
+}
+
+vars_verify--setup() {
+  if [[ "$DEPLOYDIR" == "" || "$INSTANCE" == "" || "$RELOADCOMMAND" == "" || "$BUILDSCRIPT" == "" || "$NODEVERSION" == "" || "$DOCKERNODE" == "" ]]; then
+    echo "[Error] $0 [DEPLOYDIR] [INSTANCENAME] [RELOADCOMMAND] [BUILDCOMMAND] [NODEVERSION] [NODEDOCKERIMAGE]"
+    exit 1
+  fi
+}
+
+exec--setup() {
+  cd $CURDIR
+  instance=$(basename `pwd`)
+  cp $DIR/.gitlab-ci.yml ./.gitlab-ci.yml
+  cp $DIR/.deploy ./
+  DEPLOYDIR=$(echo $DEPLOYDIR | sed 's/\//\\\//g')
+
+  RELOADCOMMAND=$(echo $RELOADCOMMAND | sed 's/\//\\\//g' | sed 's/\&/\\\&/g')
+  echo "RELOADCOMMAND: $RELOADCOMMAND"
+
+  BUILDSCRIPT=$(echo $BUILDSCRIPT | sed 's/\//\\\//g' | sed 's/\&/\\\&/g')
+  echo "BUILDSCRIPT: $BUILDSCRIPT"
+
+  NODEVERSION=$(echo $NODEVERSION | sed 's/\//\\\//g' | sed 's/\&/\\\&/g')
+  echo "NODEVERSION: $NODEVERSION"
+
+  DOCKERNODE=$(echo $DOCKERNODE | sed 's/\//\\\//g' | sed 's/\&/\\\&/g')
+  echo "DOCKERNODE: $DOCKERNODE"
+
+  sed -i 's/RELOADCOMMANDTOKEN/'"$RELOADCOMMAND"'/g' .gitlab-ci.yml
+  sed -i 's/INSTANCETOKEN/'"$INSTANCE"'/g' .gitlab-ci.yml
+  sed -i 's/DEPLOYDIRTOKEN/'"$DEPLOYDIR"'/g' .gitlab-ci.yml
+  sed -i 's/BUILDSCRIPTTOKEN/'"$BUILDSCRIPT"'/g' .gitlab-ci.yml
+  sed -i 's/NODEVERSIONTOKEN/'"$NODEVERSION"'/g' .gitlab-ci.yml
+  sed -i 's/DOCKERNODETOKEN/'"$DOCKERNODE"'/g' .gitlab-ci.yml
+
+
+  sed -i 's/RELOADCOMMANDTOKEN/'"$RELOADCOMMAND"'/g' .deploy
+  sed -i 's/INSTANCETOKEN/'"$INSTANCE"'/g' .deploy
+  sed -i 's/DEPLOYDIRTOKEN/'"$DEPLOYDIR"'/g' .deploy
+  sed -i 's/BUILDSCRIPTTOKEN/'"$BUILDSCRIPT"'/g' .deploy
+  sed -i 's/NODEVERSIONTOKEN/'"$NODEVERSION"'/g' .deploy
+  sed -i 's/DOCKERNODETOKEN/'"$DOCKERNODE"'/g' .deploy
+
+  echo "Remember to add SSH_PRIVATE_KEY + SSH_HOST_CONFIG (ssh-config options)"
+}
+
 exec--main() {
   local cmd=`basename $0`
   declare -F | grep exec-- | sed 's/declare -f exec/'$cmd' /'
